[project]
name = "threshold-scraper"
authors = ["Threshold Scraper Team"]
description = "A threshold-based token distribution platform on Stacks"
telemetry = false
requirements = []
[contracts.threshold-token]
path = "contracts/threshold-token.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
